segmentio/kafka-go

consul.go, kafka.go, kafka_test.go, reader.go
cc @achille-roussel 
I'll add some tests to cover the cancelation.
=> add proper context support

consul.go, docker-compose.yml, kafka_test.go, vendor/vendor.json
cc @achille-roussel 
Copied one of the centrifuge tests here to get it passing.
=> add more tests + update consul-go

reader.go
This PR adds the ability to configure a logger specifically to report errors on kafka readers. This is useful to avoid the flood of common logs under normal situation and only surface the exceptional events that occur within the readers.
=> add error logger

README.md
I ran across a few typos while reading this, and also made a few grammar edits while I was at it.
=> Fix some typos and grammar in README.md

reader.go
This PR make the lag reading start also when a call to SetOffset is performed.
=> readLag call in SetOffset

writer.go
=> check if conn is nil before closing it in writer.run

.gitignore, dialer.go, dialer_test.go
Added
`TLS *tls.Config`
to Dialer.  When present, Dialer will attempt to connect via TLS.  Otherwise,  standard net.Conn will be used.
=> added TLS support to Dialer

README.md, batch.go, conn.go, createtopics_test.go, message.go, protocol.go, reader_test.go, sizeof.go, write.go
kafka.Message now includes topic and partition
=> Add topic partition to message

dialer_test.go, reader_test.go, writer_test.go
reduce test time by converting time.Sleep(...) to createTopic
=> Reduce test times

conn.go, conn_test.go, createtopics_test.go, describegroups.go, describegroups_test.go, findcoordinator.go, findcoordinator_test.go, heartbeat.go, heartbeat_test.go, joingroup.go, joingroup_test.go, leavegroup.go, leavegroup_test.go, listgroups.go, listgroups_test.go, listoffset.go, offsetcommit.go, offsetcommit_test.go, offsetfetch.go, offsetfetch_test.go, produce.go, protocol.go, read.go, read_test.go, sizeof.go, syncgroup.go, syncgroup_test.go
added raw Kafka calls to conn.  rebalance will be added to Reader.
=> expanding Conn to handle kafka api calls required to support consumer groups

conn_test.go
Using a fresh broker, the tests occasionally return a NotCoordinatorForGroup error.  Using a broker that's been running for a while, I don't seem to able to reproduce the problem.
The tests that are failing are negative tests that are intended to error, it's just that every so often I get an error different than what I'm expecting.  My solution was to include NotCoordinatorForGroup as a valid error.  
My other thought was to remove the test cases as it feels somewhat as I'm testing the kafka api rather than my code.
On a separate, not I ran the test suite enough to see there are a few flappers:
* TestConn/nettest/PingPong
* TestReader/calling_Stats_returns_accurate_stats_about_the_reader
=> fixed intermittently failing test cases

reader.go
previously heartbeat opened a new (potentially TLS) connection per heartbeat.  
This changeset can best be understood by looking at lines 772-781
=> refactored Reader to share *Conn for heartbeat and offset commits. 

writer.go
This PR addresses issue #69.
* add `WriterStats` type, analogous to `ReaderStats`
* expose stats capture on `Writer`
=> add support for writer statistics

conn.go
This bug cause the producer message will be deleted very soon
=> fix bug that when time is zero, writeTime doesn't set to the msgs

docker-compose.yml, read.go, reader_test.go
I ran into some issues trying to run the benchmark. This PR fix the kafka docker image to the latest working version and fix the BenchmarkReader.
=> Fix benchmarks

reader.go, reader_test.go
=> Ensure reader leaves consumer group on graceful exit

conn.go, conn_test.go, deletetopics.go, deletetopics_test.go
This change makes the DeleteTopics function work with Kafka 0.10.0
=> Downgraded delete topics request/response to v0

conn.go, conn_test.go
This PR adds `Brokers()` to retrieve the list of brokers from the connection.
=> Add Brokers function

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
These are pretty rough and primitive still but hopefully will help improve the quality of new issues.
=> Created bug report and feature request templates

reader.go, reader_test.go
Also fix the test so that it fails when the incorrect value is used
=> Use CommitInterval as the commit interval instead of HeartbeatInterval

batch.go, compression_test.go, conn.go, message.go, protocol.go, read.go, read_test.go, write.go, write_test.go
Fix for https://github.com/segmentio/kafka-go/issues/128
=> V2 message reader

reader.go, reader_test.go
=> reader: allow empty partition assignments when joining a group

README.md, compression.go, reader.go, reader_test.go
Also added documentation for how to configure the Reader.
Fixes #198
=> Return errors on unknown compression codec

writer.go
=> Added clarifying docs on Writer batching behavior

reader.go
I'm on the fence regarding this change. The same time this result can be achieved by retrying ReadMessage manually. AT the same time adding this configuration option will streamline the interface of the library.
=> Add MaxAttempts to Reader

reader.go
Fixes #269
Introduces configuration parameters for bounds on how often to poll for new messages in the reader.
=> Add ReadBackoffMin/Max config to Reader (#269)

writer.go
We can increase the performance of the Kafka writer by avoiding unnecessary allocations when operating in async mode.
=> Reduce writer allocations in async mode

examples/consumer-logger/main.go
=> auto split kafkaURL to array

crc32.go
=> don't use io.StringWriter

write.go
Fix problem with nil keys. Currently nil keys are writed as empty byte instead of nil
=> #339 Fix problem with nil keys

reader.go
Using RetentionTime from ReaderConfig on create NewConsumerGroup
=> ReaderConfig.RetentionTime usage

message.go, message_test.go, writer.go, writer_test.go
=> Optimize message size calculation

reader.go
=> Updated constant for `FirstOffset` with correct type

consumergroup.go
* This log message should not be an error log, should be an info log instead
=> Fix log for syncing assignment

consumergroup.go, consumergroup_test.go
=> Consumer groups use cluster's retention setting by default.

transport.go
Because of the default aggregation by stack trace, it can be hard to identify what operations are initiating the calls to kafka-go because the request and response handling happens on separate goroutines started internally.
With the changes in this PR, the `kafka.Transport` will propagate pprof labels from the calling goroutine onto the goroutines handling kafka requests. This is particularly useful to help pprof aggregate CPU profiles around labels set by the program to create logical groups of where time is being spent.
This PR is based on #438
=> set pprof labels on transport goroutines

transport.go, transport_test.go
Fixes https://github.com/segmentio/kafka-go/issues/477
=> 0.4 fix tls address panic

writer.go, writer_test.go
Sets the correct balancer as passed through in the config on the writer
=> fix(writer): set correct balancer

consumergroup.go
PR #509 introduced a bug that could create infinite rebalance loops
when the Timeout is less than the RebalanceTimeout because the JoinGroup
call could timeout before the rebalance completes.
=> Fix consumer group timeout handling

README.md
https://github.com/segmentio/kafka-go/issues/511
=> README: Add SASL section

README.md
The current README includes quite a few code snippets that include no error-handling. If someone is trying to learn this library for the first time, it can make understanding why things fail much more difficult without first adding this error-handling to their own code.
It's just good hygiene in Go to handle errors, so I think our examples should reflect that, rather than try so hard to keep the code shorter.
=> docs(readme): add error-handling to example code

README.md
* add docs on how to create topics
* add docs on how to connect to leader via another connection
in response to issue https://github.com/segmentio/kafka-go/issues/440
=> add docs on how to create topics

balancer.go, balancer_test.go
LeastBytes balancer may select wrong partition, when partitions have changed.
=> fix LeastBytes Balancer logic for partition changes

README.md
resolves issue https://github.com/segmentio/kafka-go/issues/537
=> add docs to read all messages within time range

README.md, balancer.go, balancer_test.go, consumergroup.go, consumergroup_test.go, reader.go, reader_test.go, writer.go, writer_test.go
In preparation for merging 0.4 into `master` (see #438), this PR merges the latest and resolves the conflicts. A separate PR is being made to allow others to review the changes first.
=> chore: merge master and resolve conflicts

README.md
Fixes https://github.com/segmentio/kafka-go/issues/560
=> update README to documenta that we support Go 1.13+

README.md
This fixes #605 by updating the Writer section of the README to reflect the fact that setting topic on a per-message basis (ie: writing to multiple topics) is now supported.
=> docs(readme): update Writer section to include multi-topic mode

fetch.go
This PR adds the ability to use FirstOffset and LastOffset as symbolic constants when submitting Fetch requests with a kafka.Client.
=> automatically discover first/last offset in client fetch requests

balancer.go
=> fix(LeastBytes.Balancer): use mutex for slice of counters

conn.go, conn_test.go, dialer.go
Fixes https://github.com/segmentio/kafka-go/issues/697
=> expose the broker that connections are established to

heartbeat.go, heartbeat_test.go, protocol/heartbeat/heartbeat.go, protocol/heartbeat/heartbeat_test.go
Add support for sending Heartbeat requests to the Client.
=> Add Heartbeat request to client.

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Add a full Code of Conduct and Code Contribution Guidelines document.
Provide description on how best to retrieve code, fork, checkout, and commit changes.
Fixes #688
=> Add Code of Conduct and Contribution Guidelines

addoffsetstotxn.go, addoffsetstotxn_test.go, protocol/addoffsetstotxn/addoffsetstotxn.go, protocol/addoffsetstotxn/addoffsetstotxn_test.go
Implement the AddOffsetsToTxn protocol and request types.
Add Client function AddOffsetsToTxn.
=> Add AddOffsetsToTxn function to Client

reader.go
Addresses #770 
if we don't continue here we hit the errcount++ at the end of the loop
which forces us to sleep after successful reads.
=> continue in reader readLoop on success

README.md, reader.go
Fixes https://github.com/segmentio/kafka-go/issues/84
=> document CommitOffsets behavior

message.go
no very important, but a letter is a letter!
Thanks for your project by the way!
=> A very very small typo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I reviewed our issue template and thought we could provide a bit more structure to help users report issues in a format that would better support us.
If anything, adding formatted examples might be the main contribution here, as a lot of the submissions we receive have code blocks or logs pasted in standard text formatting, making it impractical for us to read.
I'm also hoping that encouraging users to submit a docker-compose file and fully functional Go program to reproduce the issue could help improve the quality of bug reports we receive. A first step in this the direction of https://github.com/segmentio/kafka-go/issues/863
=> improve issue templates

README.md, balancer.go, balancer_test.go
Hey guys, can I have some feedback on this PR please?
I've opened it due to [this issue](https://github.com/segmentio/kafka-go/issues/905).
=> ReferenceHash balancer

conn.go, conn_test.go, kafka.go
=> fix issue 971

reader.go
This change adjusts the `Reader` to intentionally close the connection on `io.ErrNoProgress`, with the expectation that a retry would likely work. Since we're explicitly handling this error/failure, we're suppressing the logs/metrics that were brought up in #932
=> feat(reader): handle io.ErrNoProgress more gracefully

reader.go
Unified use of useSyncCommits to judge
=> use useSyncCommits

transport.go
**Problem**
As mentioned [here](https://github.com/segmentio/kafka-go/issues/963#issuecomment-1279253873), metadata information was coming for all the topics in the cluster, in large clusters this number is quite high. We needed a config where we could give the topic names in order to get the metadata information only for the topics we were interested in.
=> Fix unnecessary topic metadata request

protocol/reflect_unsafe.go
=> Add float64 operations to reflect unsafe

writer.go
=> Fix code example

README.md
=> Docs: Fix import error in Writer code example in README
