- circle.yml
- conn.go
- dialer.go
- reader.go
- reader_test.go
I noticed kafka often fails saying the the requested offsets are out of range on the reader, I'm not sure why this is happening because it seems like the tests would never request an offset that's out of range so I suspect some sort of race condition within kafka (AKA a behavior that I may not be aware of).
This PR attempts to make the reader implementation more resilient to those cases by changing the behavior to always gracefully handle out-of-range offset errors:
- if the starting offset is before the first, the reader will start from the first offset
- if the starting offset is after the last, the reader will wait for the last offset to catch up by retrying periodically (with a backoff)
Please take a look and let me know if anything should be changed!
> reader improvements

- batch.go
- conn.go
- conn_test.go
- read.go
- reader.go
cc @achille-roussel 
This propagates the high watermark offset to the batch. This is used to calculate the lag of a reader by comparing the current offset to the watermark.
> add high offset (watermark) support

- reader.go
- reader_test.go
This pull request addresses a performance issue that was mainly due to the use of unbuffered channels to pass messages between the internal goroutine of the Reader and the caller of ReadMessage.
Here are profiles before and after the change:
```
$ go tool pprof ./kafka-go.test /tmp/base1.cpu
Entering interactive mode (type "help" for commands)
(pprof) top10
3440ms of 4620ms total (74.46%)
Dropped 31 nodes (cum <= 23.10ms)
Showing top 10 nodes out of 88 (cum >= 650ms)
flat  flat%   sum%        cum   cum%
1240ms 26.84% 26.84%     2800ms 60.61%  runtime.selectgoImpl
410ms  8.87% 35.71%      410ms  8.87%  runtime.unlock
360ms  7.79% 43.51%      500ms 10.82%  runtime.lock
260ms  5.63% 49.13%      280ms  6.06%  syscall.(*Errno).Timeout
250ms  5.41% 54.55%      250ms  5.41% …
```
> reduce the number of channels involved in reading messages

- README.md
- balancer.go
- conn.go
- dialer.go
- docker-compose.yml
- example_writer_test.go
- writer.go
- writer_test.go
Hey Kafka boyz, Here's the implementation of a high-level Writer API to produce messages to kafka, a couple of highlights:
- automatically discovers the available partitions for a topic
- balancing messages across partitions using the `Balancer` abstraction
- supports automatic retries on failures
- supports sync and async modes
- supports async cancellation via contexts
- gracefully closes, waits for inflight messages to be flushed before returning
I still have to add more tests for the message balancing algorithms and a section to the README but I think the code is mature enough to be reviewed now.
Please take a look and let me know if anything should be changed.
> Add the Writer type

- reader.go
- reader_test.go
The intent here is to be able to estimate the lag of a reader without having to read messages. There are times where one of our kafka consumers was failing to make progress and therefore wasn't calling ReadMessage anymore, which means the high watermark wasn't getting updated and the lag value became inaccurate since it was based on outdated information.
Please take a look and let me know if something should be changed.
> add Reader.ReadLag

- reader.go
- reader_test.go
We've run into a weird situation where when the consumer hasn't read any messages it believes that it has the entire all-time backlog of lag. This PR addresses this issue by reporting no lag until at least one message has been read to set the offset to a positive value.
> don't report lag until at least one message is read

- reader.go
- reader_test.go
This PR adds the ability to set a logger on a kafka reader to get insights into the internals, while also probably fixing a bug with offset management.
I haven't been able to really identify the root cause of the issue but this code has been running in production for a week now and the bug hasn't triggered (where it did consistently before).
The problem we were seeing was the reader being unable to make progress, its offset was always being reset to a previous value.
Please take a look and let me know if something should be changed.
> Logging + Reader bug fix

- dialer.go
- dialer_test.go
This was available on the connection object but it's a low level interface, with this change it becomes a context-aware single method call to lookup partitions of a topic.
> add higher level interface to lookup partitions of a topic

- reader.go
This adds some logic to re-establish a connection with the new leader if the current one is no longer valid.
> Fix NotLeaderForPartition error

- reader.go
- reader_test.go
- stats.go
This is a long due pull request. It adds metrics collection to the internal implementation of the kafka reader, and exposes them to the application through a new `kafka.(*Reader).Stats` method.
The `kafka.ReaderStats` structure is designed to work with [stats](https://github.com/segmentio/stats) and can be directly passed to the stats engine's `Report` method.
I've tried to add as many metrics as I could think of but if you notice anything that is missing please let me know.
> add reader stats

- reader.go
This PR changes the reader to log the original error when we fail to determine the error type.
> better unknown errors

- reader.go
This PR changes the hard 10s limit we used to have to read a full batch of messages into a 5s to 10s limit to read each message of a batch. The intent of this time limit is to act as a safety net in case the connection is dropped, but if the output channel is filling up it ends up triggering and dropping the connection.
> better timeout management

- error.go
- reader.go
- reader_test.go
Fixes #30 
When initializing the inner reader returns an offset out-of-bounds error it should simply apply the backoff logic and retry the connection later.
> fix panic on out-of-bounds error

- reader.go
This PR changes the error returned by ReadMessage to EOF when the reader has been closed, there are two reasons why we make this change:
- io.EOF is the _correct_ error for indicating that a read operation has reached the end of the data stream it was reading
- io.ErrClosedPipe maybe returned by the inner reader if the connection is lost, and would confuse the application into thinking that the reader has reached the end
This may be considered a breaking change, however it was not previously documented and doesn't break the compilation either.
Please take a look and let me know if you have any concerns.
> EOF on closed reader

- reader.go
We noticed an issue where consumers would stop making progress if they were falling behind and attempted to read from an offset that was before the first offset of a partition.
This PR addresses the issue.
> fix reading before the first offset

- writer.go
writer.go:write method return nothing on resch channels when conn==nil and w.dial() fails, so the WriteMessages method locks waiting forever some answer in the res channel
> Goroutine locking on writer.go:WriteMessages method

- batch.go
- conn.go
solution was to give the Batch its own copy of topic and partition
> resolves race condition where Batch.close called during readMessage

- README.md
- balancer.go
- balancer_test.go
by default, sarama uses the fnv1a algorithm to determine which partition to route messages to.  
To ensure that messages are routed to the same partition, I've added a Hash balancer that uses the same logic.
Even if one is not coming from sarama, having a partitioner that routes messages with the same key to the same partition is critical.
> created Hash balancer for producer compatibility with sarama

- README.md
- dialer_test.go
- joingroup.go
- joingroup_test.go
- read.go
- read_test.go
- reader.go
- reader_test.go
- rungroup.go
- rungroup_test.go
- strategy.go
- strategy_test.go
- syncgroup.go
- syncgroup_test.go
I thought I would open a pull request early to get your initial feedback on the request.  This is a working version of consumer group support for the Reader.  I've manually verified interoperability with Sarama.  In addition, I've included an automated  compatibility test with sarama.
Almost all the changes are additive.  The main change was around (*Reader).start that now supports multiple readers and an initial offset.  That said, I tried to preserve the spirit of what I believe start was doing.
Would love to get your thoughts.
> added consumer group support to Reader

- commit.go
- reader.go
- reader_test.go
@savaki I modified the `CommitMessages` implementation in the case where the reader is configured to use synchronous commits, in which case the method now actually waits for the commit to complete and any error is propagated back to the program.
> Revisit sync commits

- commit.go
- reader.go
- reader_test.go
@savaki this PR adds documentation on the `CommitMessages` method, and moves it close to `FetchMessage` in the file to make it easier to read the code (since those are closely related).
> add CommitMessages documentation

- commit.go
- commit_test.go
- reader.go
- reader_test.go
Internally, kafka-go offset is consistent with itself.  Unfortunately, not with the rest of the world.  The commit offset should be the offset of the next message to read and NOT the last message read.   Verified by running sarama and kafka-go sequentially to verify they picked up each others offsets.
Seeing as you were working in commits, I thought I would hop on your commit.
> resolves off by 1 compatibility issue with sarama.

- reader.go
The error message was a bit confusing. Read opposite to what the intended behavior. Small change to better represent the invalid use case it describes.
> fix error message for errNotAvailable

- conn.go
- message.go
If not set at the creation of the message, we need to set the message timestamp.
By not setting this timestamp, messages will be deleted at the next log cleaner iteration.
> Automatically set Time when publishing the messages

- conn.go
- conn_test.go
- createtopics.go
- deletetopics.go
- deletetopics_test.go
- protocol.go
This PR adds support for the [DeleteTopics](http://kafka.apache.org/protocol.html#The_Messages_DeleteTopics) operation. It can be useful in tests to delete test topics.
> Add support for deleting topics

- batch_test.go
- conn.go
- error.go
_Work In Progress_
Testing the hypothesis, if it is the case we should get `kafka.UnknownTopicOrPartition` when a kafka cluster goes down.
> handle empty list offset responses

- README.md
Like to add some documentation around adding TLS config to the different Conn/Reader/Writer types
> add documentation for adding TLS to Conn/Reader/Writer types

- reader.go
- stats.go
- writer.go
Go's atomic package requires that the 64bit operations, are 64-bit aligned on 32-bit systems. See the last note here: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
This PR comments about the issue and fixes two instances where atomic operations were being performed on non-aligned int64s resulting in a panic. The fix was simply to allocate the stats structs since the start of structs are guaranteed to be 64-bit aligned when allocated.
The PR also removes the unsafe usage in the stats.go file since it was not necessary.
> Fix alignment issues with stats on 32-bit systems

- writer.go
When there is no existing partition or an error occurs writing to Kafka, the `run` routine returns a classic error.
But `WriteMessage` only retries if the error is a `writerError`  (https://github.com/segmentio/kafka-go/blob/master/writer.go#L288). This PR converts the errors returned by the `run` method during the write to the partition to `writeError` errors, allowing the retry mechanism to function as expected.
Closes: #74
> Fix retry mechanism when a failure occurs on the push to kafka

- strategy.go
- strategy_test.go
In the current implementation, when attempting to assign 213 partitions to 66 members, the range strategy decides each member gets 3.22, rounded up to 4 partitions, each. This gives the first 53 members 4 partitions, one member a single partition, and the remaining 12 workers 0 partitions each. This causes almost 20% of the members to be idle.
This PR switches the strategy to instead spread the start indexes of each member evenly over the partitions, causing the difference between the min and max partition count assigned to each member to be at most 1.
Many of the existing tests for the range strategy had their output changed to different, but still valid values.
>  Fix range strategy uneven assignments when partition count not divisible by worker count

- conn.go
- conn_test.go
- reader.go
- writer_test.go
This change is intended to be non-breaking.
Since the meaning of `whence` differs subtly from `os.Seek`, name them to make the meanings obvious. Also, add the missing "seek relative to current offset" (previously whence=1 was documented as doing this, but it actually seeks to an absolute offset, whereas 0 is relative to the beginning of the partition.
> Add constants for Seek's whence and introduce a fourth strategy

- conn.go
- metadata.go
- protocol_test.go
- read.go
This change is compatible with Kafka brokers 0.10.0.0+.  It allows
us to expose the rack setting in the Broker struct.
> Upgrade Metadata Request from v0 to v1

- .circleci/config.yml
- conn.go
- conn_test.go
- createtopics.go
- createtopics_test.go
- docker-compose.yml
- findcoordinator.go
- findcoordinator_test.go
- heartbeat.go
- heartbeat_test.go
- joingroup.go
- joingroup_test.go
- leavegroup.go
- leavegroup_test.go
- offsetcommit.go
- offsetcommit_test.go
- offsetfetch.go
- offsetfetch_test.go
- reader.go
- reader_test.go
- strategy.go
- syncgroup.go
- syncgroup_test.go
The versions of many api calls made aren't compatible with kafka 0.10.1. These changes downgrade them for compatibility. This likely isn't the full set of changes needed for support, but can be a good starting point.
> Downgrade various api versions to be compatible with kafka 0.10.1

- writer.go
Cosmetic change that fixes a misspell in the godoc documentation.
> Fix typo: "individualy" is a misspelling of "individually"

- dialer.go
Sometimes it's convenient to dial Partition that comes out of LookupPartitions functions directly instead
of calling DialLeader. It saves one loop over all brokers.
It would be really convenient to have it the upstream project.
> Extract DialPartition function

- writer.go
Currently, when `WriterConfig.Async == true` you cannot capture write errors in order to diagnose problems. The only way to detect if errors are happening is via metrics, but obviously that is only an aggregate count. (since no additional tags are included)
This change adds `WriterConfig.Logger` and `WriterConfig.ErrorLogger` (mirroring `ReaderConfig`) to add support for logging within `Writer` in order to log write errors.
> feat(writer): add logger config, use to log write errors

- reader.go
- reader_test.go
This PR attempts to provide a smooth transition towards fixing the typo in the `kafka.reader.fetch.count` metric.
The idea is to produce both `kafka.reader.fetch.count` and `kafak.reader.fetch.count` for a couple of versions, and eventually remove the deprecated field (the one with the typo).
Please take a look and let me know if you have any concerns about it.
> fix kafka.reader.fetch.count metric

- reader.go
Fixes https://github.com/segmentio/kafka-go/issues/99
The value is a `int64` in the `OffsetCommit` v2/v3 types that we use, we shouldn't check against the max value of a int32.
> fix max commit retention time

- dialer.go
- dialer_test.go
Without this tweak, I was seeing the TLS client handshake error below.
```
tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```
I added same approach to inferring the ServerName from the address that is in `DialWithDialer` of `tls.go`.
> Small fix to Dialer to set the ServerName in tls.Config if it is empty.

- message.go
This is working for codecs registered as  0 and 1 as 0 and 1 in binary are 0 and 01. But for Snappy (2) this turns into a 10 and never finds the correct decoder codec.
> Use the unMasked attributes for codec resolution

- reader.go
This PR fixes #165 allowing the developer to specify `MinBytes` in the `ReaderConfig` but avoiding to set the `MaxBytes` as well with the intention to use its default built-in value (1 MB).
> Check on min and max bytes after their proper set

- reader.go
`CommitInterval` actually defaults to 0 since it's the zero value in the `ReaderConfig` struct and it's not overwritten anywhere.
> fix the ReaderConfig.CommitInterval documentation

- reader.go
This timeout is harmless and it can spam the logs so don't use the error
logger.
Fixes #170.
> reader: don't use the error logger

- batch_test.go
- conn.go
- protocol.go
I would like to merge this as a separate PR for easier review. I will need this change is implementing v2 message reader: https://github.com/segmentio/kafka-go/pull/146
I'll be using this request right after connecting to kafka cluster in order to determine which fetch requests I'm allowed to send. 
So far the plan is to implement fetch request v5. Fetch request v5 seems to have been introduced in kafka 0.11.0.0. And presumably this is the first version where server returns message sets in v2 format.
So, if fetch request v5 is available I'll be sending v5 otherwise v2.
> Add ApiVersions request

- .circleci/config.yml
`kafka-go` is getting more and more contributors using multiple versions of Kafka. To ensure proper compatibility with the supported versions, we need to test against all of them.
This PR creates a CI job for Kafka 0.11.0.1, 1.1.1 and 2.1.0.
> Test against multiple Kafka versions

- .circleci/config.yml
- conn_test.go
- version_test.go
Added a utility method to check broker version so that tests for
newer functionality can be skipped.
> Run tests for kafka 0.10

- reader_test.go
This adds a test that will pass when a Reader with a group membership successfully leaves its group on `r.Close()`
> Add test for Reader leaving its consumer group on Close()

- conn_test.go
I think the reason the test was failing is that the max fetch time sent to Kafka could in certain cases be calculated as less than the connection's read timeout.  In that case, Kafka was returning with 0 bytes and no error (as it should).  Bumping up the timeout appears to fix the issue--I have run tests multiple times in CI w/out failures.  Though of course that's like trying to prove a negative. 😉
> Increase timeout in a Conn test to avoid spurious test failure

- reader.go
- reader_test.go
Adding in a func in the handshake to watch for partition changes from the brokers. This allows kafka-go to pick up new partitions without having to restart. It does this by polling the brokers on an interval then causing a rebalance via a new call to `handshake`.
This is from breaking apart:
https://github.com/segmentio/kafka-go/pull/184
> Adding partition watcher, so Kafka-go picks up new partitions. 

- reader.go
This error can happen when a partition is moved brokers, and can be recovered from. It should be treated similar as a Leadership move which is handled in the case below.
More details: https://github.com/segmentio/kafka-go/pull/184/
>  Adding error case for UnknownTopicOrPartition into Read loop

- compression_test.go
- gzip/gzip.go
- lz4/lz4.go
Benchmarks indicate that gzip gets ~20-100% throughput increase
while lz4 goes up ~600-1000%.
> Pool gzip and lz4 readers and writers

- conn.go
- conn_test.go
This PR is in reference to the feedback on the inactive PR https://github.com/segmentio/kafka-go/pull/153. Here we're changing the name of the func to `Controller` and returning a `Broker` as requested.
> Retrieve controller

- reader_test.go
This makes me sad, but it will make me far less sad in the long term than seeing builds fail all the time. 😹
> Workaround for racy testReaderStats test

- conn.go
- write.go
This PR is for configuring isolation level in batch reading. It's also one of the steps in this story: #216.
There are two variants to configure isolation level either through configuring batch reading, as it's done here, or by configuring connection.
> Isolation level

- conn.go
Hi, we updated some exported function comments based on best practices from Effective Go. It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- writer.go
Prior, every writer to a partition had its own timer that ticked at
1/10th the BatchTimeout interval. Each tick, the code would check
whether BatchTimeout has elapsed since the prior flush and, if so,
trigger a flush.
This change makes the timer more accurate so that it only needs to tick
once every BatchTimeout interval, and only needs to begin a timeout
on the first message for a batch.
> writer: make the force flush timer accurate

- message.go
This avoids the peek/discard loop that also can result in
ErrShortRead for large messages.
> Read compressed RecordBatch messages directly into byte buffer

- batch.go
- message.go
bufio.Reader.Peek() returns ErrBufferFull if the peek size is larger than the buffer size. Grow the provided slice up to cap.
> Fix full buffer errors.

- .circleci/config.yml
- compression.go
- compression_test.go
- conn.go
- gzip/gzip.go
- produce.go
- protocol.go
- read.go
- write.go
- zstd/zstd.go
This PR adds the zstd compression algorithm available since Kafka 2.1.0 with the required internal fetch and produce request versions.
Note about this PR : in this PR we are using github.com/DataDog/ztsd which is a Go wrapper around the C implementation of ztsd. Due to that using zstd will require cgo which is quite unfortunate.
> Add zstd compression

- reader.go
- reader_test.go
Official Kafka clients (librdkafka, java) do not throw an error in
this case. Instead, they hand back empty assignments to all the
consumers. The partition watch functionality can be used to trigger
a rebalance if the topic comes into existence later.
> Don't fail consumer group assignment if topic does not exist

- batch.go
This PR adds `func (*Batch) Err() error`, see the documentation for detailed explanations about the use cases that this new API solves for.
> expose batch error

- conn.go
- message.go
- message_test.go
We have some topics that are low traffic. On topics like this, we are getting a lot of error messages, such as `the kafka reader got an unknown error reading partition 17 of some_topic_name at offset 577667: unexpected EOF`
This error originates here: https://github.com/segmentio/kafka-go/blob/master/conn.go#L806
When there are no messages to be read, kafka returns an empty response body, and `highWaterMark == currentOffset`, however `newMessageSetReader` treats this as a bad response.
This change modifies `messageSetReader` to allow it to be empty, and check for this case.
> handle empty batch message set

- testing/version.go
- testing/version_test.go
Shorter(including empty) kafka versions are perceived as satisfying atLeast requirement.
> Pad shorter version with zeroes

- conn.go
- conn_test.go
- go.mod
- go.sum
This PR adds a flag that can be passed to the `kafka.(*Conn).Seek` method as an optimization to avoid making a metadata request when positioning the connection.
> add kafka.SeekDontCheck

- read.go
- read_test.go
- write.go
I was looking into optimizing varint decoding because we have a use case where during CPU-intensive work, ~15% of the time is spent on this code path.
While writing the initial benchmarks to validate the change I noticed that encoding and decoding was broken for large integer values due to some mistakes in the way zig-zag encoding was being handled. This probably never triggered in practice because the varints are not used to encode values in the 2^56~2^64 range, but we're better off with a fix anyways ;)
The optimization yielded good results on the read path:
```
benchmark                old ns/op     new ns/op     delta
BenchmarkWriteVarInt     20.8          20.3          -2.40%
BenchmarkReadVarInt      93.3          38.0          -59.27%
```
> fix and optimize varint encoding

- compression.go
- compression_test.go
- go.mod
- go.sum
- gzip/gzip.go
- lz4/lz4.go
- message.go
- snappy/snappy.go
- snappy/xerial.go
- snappy/xerial_test.go
- write.go
- zstd/zstd.go
This PR modifies the compression codec API to employ `io.Reader` and `io.Writer` instead of working with byte slices. The upside is the amount of memory that gets allocated internally is greatly reduced, and we pave the way for better internal abstractions to build more efficient programs with kafka-go.
This is a breaking change in the API, but I think it's OK since these packages are intended to work with kafka-go, and programs shouldn't use these directly (maybe we'll bump to 0.3.0 on the next release?).
Here are comparisons of the compression benchmarks taken before and after:
```
benchmark                            old ns/op     new ns/op     delta
BenchmarkCompression/GZIP1024        48754         57090         +17.10%
BenchmarkCompression/GZIP4096        116650        110110 …
```
> Stream compression

- message.go
- message_test.go
This should better capture the spirit of the empty batch by
surfacing the error code that indicates the broker wasn't able to
return new messages before the max wait time passes.
> Use RequestTimedOut on empty batch instead of errShortRead

- snappy/xerial.go
In cases where the xerial reader requires more bytes than available
in the decompressed buffer, we currently get corrupt data.  That
would result in the reader halting.  Clearing out x.output and
x.header ensures that this condition is handled gracefully.
> More aggressive resets of state in xerial reader

- dialer.go
- sasl/plain/plain.go
- sasl/sasl.go
- sasl/sasl_test.go
- sasl/scram/scram.go
While is a breaking change for the sasl.Mechanism interface, it's
not expected that library clients are implementing said interface
as Kafka only accepts a very specific set of mechanisms.
Fixes #317
> Make sasl.Mechanism safe for concurrent use

- conn.go
The value `1<<31` exceeds the limit of 32-bit integer, which will cause compile failure in 386 arch.
Reducing it to 1<<30 (as suggested by @achille-roussel in [!330](https://github.com/segmentio/kafka-go/pull/330)) solves the error and preserves the flag's functionality.
> decrease value of seekdontcheck to avoid integer overflow in 386 arch

- buffer.go
- compression.go
- write.go
This PR should wrap up optimizing the write path of `*kafka.Conn` by recycling the buffers where compressed messages are written.
> recycle compression buffers

- .circleci/config.yml
- writer.go
- writer_test.go
https://github.com/segmentio/kafka-go/issues/345#issuecomment-528451990
> We saw a similar issue on our production boxes, we have a metrics topic where we observed weird behavior, messages are successfully published for 25 mins, then we see broken pipe errors for the next 25 mins, and then the cycle continues.
> Upon further investigation we found that,
> We publish one message per 5 mins, and there are 5 partitions, so the Kafka writer sends 1 message to each partition every 25mins. Under the default settings, the Kafka broker closes a connection if it doesn't receive any new message in the last 10 mins. But the Kafka writer doesn’t know that the connection has been closed, so when it tries to a second message on the same connection, it sees broken pipe errors.
> So for the next 25 mins …
> Add max idle conn timeout for Writer.

- conn.go
- recordbatch.go
- write.go
@achille-roussel @stevevls Would you be willing to merge this refactoring?
As I was working on adding transaction support to batches I realized that constructing batches deep in the invocation stack is very tedious as all their parameters should be passed to V3 and V7 functions.
I extracted record batch structure and now it's constructed one level above the writeProduceRequest functions. This way if we need to add arguments to recordBatches we can do it without touching signatures of writeProduceRequest functions.
> Extract record batch structure

- reader.go
They were being logged to the error logger, which caused error-level
logs to be written frequently when topics had no messages to consume:
```
the kafka reader got an unknown error reading partition 14 of my_topic at offset 80: EOF
```
> Log EOF errors to standard logger

- consumergroup.go
- consumergroup_test.go
- logger.go
- reader.go
- reader_test.go
- writer.go
At the moment there is no way to configure custom logger for Writer. For example i want to use structured logger like logrus or zap for Writer interface. 
This patch introduces new API which provide possibility to set custom logger for Writer with backward compatibility not to break current kafka-go users.
> Introduced new pluggable logging API

- conn.go
https://github.com/segmentio/kafka-go/pull/302 did not work as well as I expected, and ended up burning CPU without making much progress.
This PR reverts the change and replaces it with a different approach: we have no use cases for multiplexing multiple requests on connections for now, so detect the common case where there is only one goroutine using a connection, and if the correlation IDs don't match we know that we have corrupted input.
> revisit wire corruption detection

- error.go
Main goal is to update the list of `Temporary` errors.  My application dropped many messages when a Kafka broker was down due to a `NotEnoughReplicas` error, so I thought it would be good to update them all. 
https://kafka.apache.org/protocol#protocol_error_codes specifies which errors are retriable.
> Update `Error` consts and `Error.Temporary()`

- conn.go
This PR modifies the mechanism for negotiating API versions between the client and the broker so it happens lazily on first use of the connection instead of during the construction of the `kafka.Conn` value.
It addresses a rare edge case where clients could stay stuck waiting for a response during the construction of the connection, because no deadlines were configured yet.
> lazily load API versions

- conn.go
- conn_test.go
- metadata.go
Ensure all topic partitions are returned when the connection does
not have a configured topic and the caller does not pass any
topics as arguments.
Fixes #381
> Fix behavior of Conn.ReadPartitions() when no topics specified

- listgroups.go
- listgroups_test.go
None of the protocol types are exported, this type wasn't used in any public APIs either.
> don't export listGroupsResponseV1

- conn.go
- createtopics.go
- deletetopics.go
- protocol.go
- protocol_test.go
- write.go
- write_test.go
This main change in this PR is the addition of a formatting method on the `kafka.ApiVersion` type.
I also extended support for more API keys and fixed some names to match the kafka protocol documentation in https://kafka.apache.org/protocol.html#protocol_api_keys
> add kafka.ApiVersion.Format

- go.mod
- go.sum
- zstd/zstd.go
Follow-up on stale #303 with full use of the streaming API from @klauspost.
Decompression is slower while the (default) compression ratio went down from 5 to 3.
```
name                           old time/op    new time/op    delta
Compression/zstd/compress-4      5.64ms ± 2%    3.02ms ± 2%   -46.42%  (p=0.000 n=10+10)
Compression/zstd/decompress-4     911µs ± 2%    2386µs ± 2%  +162.10%  (p=0.000 n=10+10)
name                           old speed      new speed      delta
Compression/zstd/compress-4    21.0MB/s ± 2%  44.3MB/s ± 2%  +111.39%  (p=0.000 n=10+10)
Compression/zstd/decompress-4  2.13GB/s ± 2%  0.81GB/s ± 2%   -61.85%  (p=0.000 n=10+10)
```
> Replace Zstandard wrapper with native Go implementation

- example_groupbalancer_test.go
- groupbalancer.go
- groupbalancer_test.go
This strategy attempts to optimize round trip transfer time between
brokers and consumers in addition to minimizing inter-zone data
transfer costs in cloud environments.  Currently only supports AWS.
> Added RackAffinityGroupBalancer strategy

- writer.go
Currently, an async writer does not retry failed messages – a temporary network connection error will result in lost messages.
This change attempts to improve this situation by retrying messages for both sync and async writers.
In order to implement this, I moved the existing retry loop down the stack to the internal `writer` type. I'm *fairly* sure this will not break the existing behavior of sync writers, but I'd appreciate some extra eyes on this.
> async writer retries

- reader.go
io.EOF is used as a marker that a batch of messages has been
completely read.  The batch will repackage an io.EOF from the
underlying connection as an io.ErrUnexpectedEOF.
The previous behavior closed the connection on an io.EOF and
restarted the reader loop, which will be much less efficient than
continuing to use the connnection.
> Don't close connection when end of batch is read correctly

- consumergroup.go
when we use defaultRetentionTime -1
we get the gen
gen := Generation{
ID:              generationID,
GroupID:         cg.config.ID,
MemberID:        memberID,
Assignments:     cg.makeAssignments(assignments, offsets),
conn:            conn,
done:            make(chan struct{}),
retentionMillis: int64(cg.config.RetentionTime / time.Millisecond),
log:             cg.withLogger,
logError:        cg.withErrorLogger,
}
the retentionMillis of gen is 0
request := offsetCommitRequestV2{
GroupID:       g.GroupID,
GenerationID:  g.ID,
MemberID:      g.MemberID,
RetentionTime: g.retentionMillis,
Topics:        topics,
}
then offsetcommit request is bad with the RetentionTime=0
the group offset is expired when all consumer is down
kafka server params offsets.retention.minutes is not work
so when we …
> fix offset commit bug

- dialer.go
Looks like this originates from #133 when we added `DialPartition` as a top-level function.  All of the other public functions on the `Dialer` will eventually traverse `DialContext`, which takes into account the timeout and deadline.  `DialPartition`, however, can't go through `DialContext` because it needs to add the topic+partition on the `Conn`.  Unfortunately, that means that the timeout and deadline were not getting applied.
Fortunately, every public function on the `Dialer` does eventually go through the unexported `connect` function, so that's a logical place to move the code that applies the timeout/deadline.
> Ensure Dialer.DialPartition honors configured timeout and deadline

- stats.go
Using LoadInt64 and then AddInt64 can lead to incoherent results if
snapshot() is called twice at the same time.
We recently encountered this situation in production and it produced a panic somewhere else because of the negative number.
> Use SwapInt64 to snapshot counters

- zstd/pool.go
- zstd/zstd.go
- zstd/zstd_test.go
**Description**
Using `sync.Pool` to pool encoders/decoders that are not eligible for
deallocation once the pool loses their reference leads to goroutine & mem leaks.
**Kafka Version**
Irrelevant; library issue.
**To Reproduce**
See added test.
**Expected behavior**
There should be no memory or goroutine leaks.
**Additional context**
The docs from `sync.Pool` state:
> Any item stored in the Pool may be removed automatically at any time without
> notification. If the Pool holds the only reference when this happens, the
> item might be deallocated.
`zstd.Decoder`s spin up their own goroutines, which hold a strong ref to owning
decoder. When `decPool` downsizes (usually on GC runs), an arbitrary number of
decoders are evicted from the pool. Since their goroutines are still running
(observed: …
> Fix zstd decoder leak

- transport.go
The dial function is configurable on the `kafka.Transport` type, which receives a context as first argument. Inheriting from the context that originally sent the request helps programs pass values throughout the abstraction layers.
> propagate the caller's context to the dial function

- writer.go
- writer_test.go
CC @abuchanan-nr 
There were a few issues with #382 that we should address. In the meantime, this PR:
- reverts the change, and
- updates `testWriterMaxAttemptsErr` to ensure it's testing the behavior it thinks it's testing.
To summarize the issues we know of with #382:
- `WriteMessages` returns early with initial write errors rather than waiting for retries, as we write directly to the response channels before retrying.
- The response channel can become full after a batch fails, and further retries are blocked on writes to the full channel.
- There is a subtle behavior change that was perhaps not considered well enough: rather than `WriteMessages` blocking on sleeps during retry, the background `partitionWriter` threads are now doing the sleeping. This may mean that other concurrent …
> Revert #382

- client_test.go
- docker-compose.010.yml
- protocol/buffer.go
- protocol/record_v1.go
This PR addresses an issue where producing to a kafka 0.10 broker using kafka-go 0.4 would result in silently dropping parts of the batch.
The issues was an inverted logic in a error check, which caused compressed message sets to be truncated after writing the first buffer page. This code path was specialized for the message v1 format, which explains why it didn't hit on kafka brokers in order version (which use the version 2 of the message format).
I added a test which allowed me to reproduce the issue and verify that the changed corrected the behavior.
> 0.4: fix short writes

- dialer.go
This PR adds the ability to configure the function used by `kafka.Dialer` to establish network connections. This customization is useful to add monitoring on the network connections opened by the various components (Reader, Writer, etc...),  as they can all be configured to use a `kafka.Dialer`.
I chose to name it `DialFunc` because the `kafka.Dialer` type already had methods called `Dial` and `DialContext`, but I'm open to better naming suggestions.
> make the dial function configurable on the kafka.Dialer type

- conn.go
- conn_test.go
This fixes a bug where ReadBatchWith could incorrectly return `io.EOF`
in certain `errShortRead` scenarios.  Since `io.EOF` means the batch
was handled correctly, this could cause consumers to continue to use
a connection that is in a bad state.
This also adds a MaxWaitTime option that can be used to improve the
way that the conn deadline and the fetch request interact.  Instead
of trying to calculate a correct timeout and change the max wait
time, this allows the caller to explicitly configure both the wait
and the deadline independently of one another.
> ReadBatchWith bug fix and new MaxWaitTime option

- protocol/buffer.go
- protocol/buffer_test.go
- protocol/encode.go
- protocol/prototest/prototest.go
- protocol/prototest/reflect.go
- protocol/record_batch.go
- protocol/record_batch_test.go
- protocol/size.go
This PR is making an API change to the `kafka/protocol` package, modifying the `protocol.Bytes` interface to expose the number of bytes remaining to read instead of the full size of the original byte sequence.
Using `Len` instead of `Size` is more relevant, especially in cases where a program would read a header off of the byte sequence, then hand off processing of the remaining bytes to a different part of the program. On the second stage, the original size becomes irrelevant, forcing the application to provide its own counting.
> 0.4: modify protocol.Bytes to expose the number of remaining bytes instead of the full size of the sequence

- reader.go
This should help redirect folks to FetchMessage instead when there
is a need to manually commit offsets.
> Update Reader.ReadMessage offset documentation.

- consumergroup.go
- consumergroup_test.go
Since the Conn does not have a timeout by default, it's possible for a
connection to hang if the remote side crashes before responding.  This
PR ensures that every interaction with the broker has a deadline so that
the consumer group won't get stuck if the coordinator goes down.
> consumer groups: ensure read deadline is set on broker interactions

- reader.go
- reader_test.go
When the high-level Reader API is used, e.g. when calling
Reader.FetchMessage, and the Reader is configured with a non-empty
GroupID, make sure that the call returns an error when the call to
ConsumerGroup.Next fails. This can happen, for example, when the Kafka
server isn't reachable.
The call will fail only after Reader.config.MaxAttempts attempts
calling ConsumerGroup.Next were performed internally by Reader.run
and failed.
Previously, Reader.FetchMessage blocked even when the Kafka cluster
could not possibly be reached, making it impractical to distinguish
between not getting messages because there are none and not getting
messages because we cannot connect to the server.
> Fix Endless waiting for consumer connection (#227)

- writer.go
- writer_test.go
This updates the `Writer` to check for the partition writer before attempting to write to it, which avoids the panic uncovered by #517. In conjunction with #519, this will help us uncover other balancer bugs in the future, since this is an interface that could easily be a custom implementation.
> fix(writer): check for partition writer before attempting to write

- transport.go
- writer_test.go
This also includes a new regression test in writer_test.go, because the previous tests were not testing RequiredAcks = 0.
> Fix for panic when RequiredAcks is set to RequireNone

- client_test.go
- dialer.go
- resolver.go
- transport.go
- transport_test.go
Based on #438, this PR adds a new `Resolver` field of type `kafka.BrokerResolver` to the `kafka.Transport` type.
This field is intended to be used to customize the resolution of brokers to IP addresses, which gives a powerful hook into the dispatch of requests to brokers.
I've added documentation in the code, let me know if you have any concerns about the change.
> 0.4 broker resolver

- README.md
This pull request adds documentation on how to get a list of all topics in kafka.
This documentation addresses how to list topics in the current version of kafka-go without adding new functionality.
This removes the need for this PR: https://github.com/segmentio/kafka-go/pull/520
> add docs on how to list topics

- writer.go
We've decided that fixing the lack of support for 0 required acks is not going to happen in v0.3, due to the extra complexity to add this coupled with the fact that v0.4 already includes support for this. This documentation update makes this clear while recommending users upgrade if needed.
> docs(writer): indicate that v0.3 does not support 0 required acks

- transport.go
Fixes #542 
The authenticateSASL was called before getting api version.
This resulted incorrect apiversion (0 instead of 1) when
calling saslHandshakeRoundTrip request
> Fix sasl authentication on writer

- dialer.go
- dialer_test.go
- writer.go
This PR improves the support for a custom `Resolver` by allowing it to return a port that overrides the original address. I took the opportunity to consolidate this same logic to a helper function and added some test cases for each of the scenarios I could think of.
This should fix #231
> improve custom resolver support by allowing port to be overridden

- protocol/cluster.go
- protocol/error.go
- protocol/fetch/fetch.go
- protocol/listoffsets/listoffsets.go
- protocol/produce/produce.go
- protocol/protocol.go
- transport.go
The goal of this PR is to reduce the memory footprint of internal data types by using `int16` or `int32` instead of `int` where possible.
The switch also brings extra type safety because we don't need to convert integers types to `int` anymore, allowing for stricter compiler checks.
> 0.4: reduce memory footprint

- README.md
This pr resolves issue https://github.com/segmentio/kafka-go/issues/540. This PR updates the documentation so that it is consistent with `KAFKA_AUTO_CREATE_TOPICS_ENABLE` config option.
> correct kafka create-topics docs

- message.go
- writer.go
- writer_test.go
This PR adds support for writing messages to topics dynamically with a single writer.
Previously, you needed to define `Writer.Topic` and it was always required. Now, if you choose not to specify this configuration, then `Message.Topic` **must** always be set for each written message.
These patterns are mutually exclusive, to help avoid some potential pitfalls, such as consuming a message from 1 topic and auto-writing it back to the same topic in an infinite loop. If both the writer and a message are configured with a topic, an error will be returned. In the opposite case, if neither the writer nor the message are configured with a topic, an error will be returned.
This should address a few issues that have been created:
- #553 
- #53
> feat(writer): add support for writing messages to multiple topics

- .circleci/config.yml
- conn_test.go
- createtopics_test.go
- docker-compose-241.yml
- protocol/createtopics/createtopics.go
- protocol/decode.go
- protocol/encode.go
- protocol/protocol.go
- protocol/protocol_test.go
- protocol/record_v2.go
- protocol/request.go
- protocol/response.go
- protocol/size.go
This change updates kafka-go to support the "flexible" message format described in [KIP-482](https://cwiki.apache.org/confluence/display/KAFKA/KIP-482%3A+The+Kafka+Protocol+should+Support+Optional+Tagged+Fields). Among other changes, the new format adds optional "tagged fields" into API messages and also makes the encodings of strings and arrays more compact.
The values of the tagged fields aren't used for much yet (I think), but we need to support the new, "flexible" format to get the latest API versions described in the [Kafka protocol guide](https://kafka.apache.org/protocol).
The proposed interface is to support tagged fields via a new, `tag=` property in the existing protocol struct tags, e.g.:
```
type Request struct {
[required fields]
TaggedField0 `kafka:"min=v1,max=v3,tag=0"` …
```
> Add support for flexible messages

- reader.go
following [official document](https://kafka.apache.org/documentation/#fetch.min.bytes)
> The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.
> fix default fetch.min.bytes to 1,

- batch.go
- transport.go
This allows to commit processed batch with:
```go
gen.CommitOffsets(map[string]map[int]int64{
"topic": map[int]{
batch.Partition(): batch.Offset(),
},
})
```
> Export Batch.Partition

- message.go
Other libraries seems to be doing:
https://github.com/Shopify/sarama/blob/8c3fe6939f5667b9390af8865f834995182b8b58/record.go#L104
https://github.com/apache/kafka/blob/927edfece3db8aab7d01850955f9a65e5c110da5/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java#L356
https://github.com/dpkp/kafka-python/blob/a27ab881726ed1a2d952867a1fa266573165d6aa/kafka/record/default_records.py#L241
Might fix #457, not sure if it was due to an actual corrupted record or a bug elsewhere in the decoder.
> Ensure headerCount is positive before making headers slice

- reader.go
I'm using `kafka-go` library in a bunch of my services and sometimes I get an error of the following form in my logs (coming from `kafka-go` library): 
```
kafka reader failed to read lag of partition %d of %s
```
but it is not clear what causes it, so I suggest we attach the original `err` in the message (if we are interested in this message being logged in the first place).
This PR adds `err` to this logged message.
> Improve `reader` error messages

- error.go
- findcoordinator.go
- findcoordinator_test.go
- FIndCoordinator implementation that utilizes the `kafka.(*Client)` abstraction.
- A tiny unit test for the same.
---
According to [this design doc](https://docs.google.com/document/d/11Jqy_GjUGtdXJK94XGsEIK7CP1SnQGdp2eF0wSw9ra8/edit#heading=h.dz78fc8xlsd5), the first step in implementing a **Transactional Producer** is looking for a TransactionCoordinator for the specified transactionalId using `FindCoordinatorRequest`. 
---
This PR is a step towards solving #233
CC: @achille-roussel
> Kafka Client FindCoordinator implementation

- conn.go
- conn_test.go
- go.sum
- reader.go
This PR aims to address some concerns raised by #607 and #608 by adding some much-needed clarity on the `MinBytes` and `MaxBytes` configuration used by `Reader` and `Conn.ReadBatch`.
In the case of `ReaderConfig`, default values are documented more clearly, and should be configured explicitly in the event of problems described later on.
In the case of `Conn`, using it with no defined value (ie: 0) for `MinBytes` and `MaxBytes` has undefined behavior. Upon adding a test case for this, it can be observed that in Kafka 0.10, this configuration will result in a batch error, but Kafka 0.11+ are able to handle this without issue. As such, the test case will give an exception to 0.10 and we can revisit if this behavior seems to regress in future versions of Kafka.
> Clarify Min/Max Bytes config for consumers

- batch.go
- message.go
Sometimes I need read HighWaterMark while reading messages.
https://github.com/segmentio/kafka-go/issues/373
> Added HighWaterMark to Message

- go.sum
- kafka_test.go
- reader.go
- reader_test.go
This change allows the `Reader` to consume from multiple topics when being used with a consumer group. To opt into this behavior, you supply `config.GroupTopics` instead of `config.Topic`, the default behavior and config is unchanged.
The following open issues would be resolved by this change:
- #595
- #564
I've added test cases for several permutations of this new config:
- `Topic`
- `GroupTopics` (one value)
- `GroupTopics` (multiple values)
> feat(reader): allow consuming from multiple topics with a group

- error.go
the previous implementation does not properly unwrap errors to check if it is a `net.Error`, which was wrapped here:
https://github.com/segmentio/kafka-go/blob/master/produce.go#L139
```
return nil, fmt.Errorf("kafka.(*Client).Produce: %w", err)
```
this leads this issues where the error is not correctly handled when calling `isTemporary` or `isTimeout`
```
error writing messages to TOPIC (partition 12): kafka.(*Client).Produce: dial tcp IP:21948: i/o timeout
```
specifically in the code block here in `writeBatch`
https://github.com/segmentio/kafka-go/blob/master/writer.go#L780-L782
```
if !isTemporary(err) {
break
}
```
> update isTimeout and isTemporary to properly unwrap errors

- writer.go
This fixes #618 by using a bespoke error message rather than returning what appears to be a kafka error code, which is confusing. This should make diagnosing this invalid configuration issue much more straightforward.
> fix(writer): do not use kafka error code for invalid config

- protocol/decode.go
- protocol/encode.go
Fixes #651.
I'm not 100% sure this is the best fix, but it does work.
> Cache version specific encoders/decoders.

- reader.go
**What**: Document the default value for `ReaderConfig.MaxWait`
**Why**: Makes it clearer — the reader of the configuration does not need to look into the implementation to know the default
**How**: Add a comment on top of the MaxWait definition
Source where the default is being set:
https://github.com/segmentio/kafka-go/blob/master/reader.go#L629 :
```
if config.MaxWait == 0 {
config.MaxWait = 10 * time.Second
}
```
Disclaimer: Not used to contribute to OS projects .
Thanks: For the time dedicated creating/maintaining the project
> Document default value for ReaderConfig.MaxWait

- writer.go
Background
Was wondering what the default value of RequiredAcks was and was looking across writer.go and writer_test.go files. 
This PR is to help people like me know the same without wondering if there is an override of the same, down the call hierarchy
> Explicitly document defaults to RequiredAcks and Async

- error.go
- writer.go
After upgrading to 0.4 (v0.4.16) from 0.3 we noticed that if a broker goes down in our kafka cluster, the ongoing writes to its partitions are failing with network connection errors and without any retry attempts.
That causes these writes to fail although they would have succeeded if retried due to the other healthy brokers in the cluster taking the partitions leadership.
I think that although network connection errors are not considered temporary, they should be treated as transient errors in this scenario, as the writer is usually working against a cluster of brokers that tolerates server failures (up to the configured replication factor).
In this PR I’ve added another condition to the breaking retry loop check that validates that the received error is not a transient network error …
> Retry the writing of messages on transient network errors

- protocol/apiversions/apiversions_test.go
https://kafka.apache.org/protocol.html#The_Messages_ApiVersions
This PR includes the following commits:
- https://github.com/segmentio/kafka-go/commit/959e305d202f34c50d064d46b836cff7862f51c3: add unit tests for `protocol/apiversions`
> protocol/apiversions: add protocol/apiversions unit test

- transport.go
- transport_test.go
Whilst I've made the changes that were agreed in the [GitHub issue](https://github.com/segmentio/kafka-go/issues/672), I haven't done any testing. Please advise on any testing you'd like me to do, above and beyond the unit tests that I assume will be run automatically on the PR after I've submitted it.
Note: I will endeavor to test that this change _actually fixes_ the issue on Monday when I'm back at work (and have access to the codebase where the issue presents).
> Only refresh metadata on success (#672)

- protocol/alterconfigs/alterconfigs_test.go
- protocol/createpartitions/createpartitions_test.go
- protocol/deletetopics/deletetopics_test.go
- protocol/electleaders/electleaders_test.go
Document: https://kafka.apache.org/protocol.html
This PR includes the following commits:
- https://github.com/segmentio/kafka-go/commit/b4e6be33b704cd8ac268f30adfa2600ad834130a: protocol/alterconfigs
- https://github.com/segmentio/kafka-go/pull/695/commits/c859f72577b5e59db9345335bc2cb46c09b1de6a: protocol/createpartitions
- https://github.com/segmentio/kafka-go/pull/695/commits/4fac6aa9e89f3ffb9d8a8b40ac4b5c0209bdd3c1: protocol/deletetopics
- https://github.com/segmentio/kafka-go/pull/695/commits/2c3018278fbf51aca622d0e35b6cd1c9c974098d: protocol/electleaders
> add unit tests for protocol/

- compress/compress_test.go
- consumergroup_test.go
- describegroups_test.go
- listgroups_test.go
- reader_test.go
- writer_test.go
- Increase some timeouts
- When creating a test topic, block until it's ready
- Wrap some errors to help debug tests 
Tests do seem to run more reliably (ran with `-count=20` and they don't fail as often now), but the downside is that they take longer to run (~2-3 min instead of ~1m) 
I broke this out of #719 because I kept getting intermittent failures there, and I'm trying to isolate them away from the refactoring changes.
> Make Writer tests more resilient

- writer.go
- writer_test.go
Attempt to preserve message order across batches.
Fixes #686
> Preserve message order across batches.

- protocol/response.go
When writing flexible messages, WriteResponse was not writing the tag buffer size of 0 causing `prototest.TestResponse` to fail for flexible responses.
> Write tag buffer size for flexible responses.

- initproducerid.go
- initproducerid_test.go
- protocol/initproducerid/initproducerid_test.go
Ran into a case testing vs Kafka 2.6.0 where the additional fields were needed.
> Support more of the InitProducerID api.

- addpartitionstotxn.go
- addpartitionstotxn_test.go
- client_test.go
- conn_test.go
- endtxn.go
- initproducerid_test.go
- protocol/addpartitionstotxn/addpartitionstotxn.go
- protocol/addpartitionstotxn/addpartitionstotxn_test.go
- protocol/endtxn/endtxn.go
- protocol/endtxn/endtxn_test.go
Implement AddPartitionsToTxn function for kafka.Client
> Add AddPartitionsToTnx to Client.

- README.md
Add a section to README.md explaining our choice
to  rename the default branch of the repo.
> Update readme to explain default branch change

- README.md
- createpartitions_test.go
- fetch.go
- go.mod
- protocol/reflect.go
- protocol/reflect_unsafe.go
- read_test.go
- reader_test.go
- write_test.go
- writer_test.go
I ran `gofmt -s` to address some of the issues reported by https://goreportcard.com/report/github.com/segmentio/kafka-go
I also changed the minimum required Go version to 1.15 since older versions aren't being maintained anymore.
> fix formatting + require Go 1.15

- conn.go
- conn_test.go
- describegroups.go
- describegroups_test.go
- reader_test.go
This change fixes how member metadata is decoded in kafka-go's `DescribeGroups` implementation. Although the [top-level protocol spec](https://kafka.apache.org/protocol#The_Messages_DescribeGroups) just says that this metadata is "bytes", it's actually encoded using the consumer protocol spec described [here](https://github.com/apache/kafka/blob/2.4/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerProtocol.java#L37). 
The latest version of this spec allows consumers to set an `OwnedPartitions` field that may be used for cooperative rebalancing. The current implementation does not handle this extra field, which leads to a "Got non-zero number of bytes remaining ..." errors when decoding the response. Users have reported this error when running `get lags` in …
> Fix member metadata decoding and remove deprecated describeGroups API

- compress/compress.go
- compress/compress_test.go
- produce.go
- produce_test.go
This PR implements the standard `encoding.TextMarshaler` and `encoding.TextUnmarshaler` interfaces on the `kafka.RequiredAcks` and `kafka.Compression` types.
The intent is to facilitate loading and saving of these configuration values via textual representations; a common use case would be to have them provided in a configuration file, or on the command line of a kafka producer.
> add encoding.TextMarshaler and encoding.TextUnmarshaler implementations

- conn.go
- conn_test.go
Data for each partition returned by Conn.ReadPartitions includes the
list of replicas and the ISR for the partition. The broker data is
copied from the list of currently available brokers, retrieved from
Kafka metadata. It can happen that a broker is not present in metadata
(due to being down, for example), but still listed as a replica for a
partition. (For example, broker 2 may be down but the ID 2 can still be
listed as a replica for a partition.)
The logic that copies broker data from the list of available brokers
into partition data now omits any that are not present in the metadata
list. Without this change, partition data receives the copy of a nil
object in its replica or ISR list (ID 0, host nil, default port 9092),
which is useless.
> Check for broker existence when forming partition replica and ISR lists

- transport.go
- writer.go
- writer_test.go
Potential Fix for #683 
Writer now sets AutoCreateTopics to true when calling for metadata.
Transport will now make a metadata request to the server if the metadata cache does not contain the requested topic and AutoCreateTopics is true. We then update the metadata cache after sending the metadata request to the server.
> Allow Writer to automatically create topics.

- dialer.go
- sasl/sasl.go
- transport.go
Picking up from https://github.com/segmentio/kafka-go/pull/563 and https://github.com/segmentio/kafka-go/pull/598, this PR only does the necessary changes to have additional metadata propagated to the authentication functions so it can be used for authenticating. Currently it's only the address (needed by GSSAPI).
I chose the context approach because it requires the least amount of changes to existing code.
> feat(sasl): enrich authentication context with metadata

- address.go
- conn.go
- dialer.go
- sasl/sasl.go
- transport.go
Follow up to https://github.com/segmentio/kafka-go/pull/725, this PR adds a `Port` field to the `sasl.Metadata` type as a way to ensure that the `Host` does not contain the port number. This would be helpful to the implementation of https://github.com/segmentio/kafka-go/pull/763
> add port to SASL metadata

- builder_test.go
- message_test.go
Uses of time.UnixMilli() introduced recently, which only work with Go
1.17 or higher, are replaced with equivalent code that works under Go
1.16. If/when this module moves past Go 1.16, these changes may be
reverted.
> Ensure tests run under Go 1.16

- .circleci/config.yml
- conn.go
Seems like In newer versions of Kafka the high water mark being equal to the offset does not mean there are no messages in the batch.
> Nettest fix

- consumergroup.go
- consumergroup_test.go
Currently, there is a `sync.WaitGroup` that is used for process accounting
with go routines started by `Generation.Start`.  It is used when a
generation is ending to ensure that all of the Start-ed functions exit
before the next generation can start.  There is an edge case that can
cause panic as written up in #786 due to unsafe use of the WaitGroup.
Basically, it is possible that `close()` is already in process and is
waiting on `WaitGroup.Wait()` when `Start()` comes in and calls
`WaitGroup.Add(1)`.
The contract of `Start()` is that the provided function is to be run.
Code in the wild may depend on this behavior, so it's not an option to
return from `Start()` without running the provided function.
Accordingly, this PR updates the code to coordinate between close() and
`Start()` such …
> Fix a rare panic during consumer group rebalance

- example_consumergroup_test.go
- example_groupbalancer_test.go
- writer.go
Example tests are renamed to fit required naming conventions. This
caused them to be relocated in generated docs.
Also, a minor problem with writer.newBatchQueue is fixed, in order to
avoid an unnecessary copy of a newly created object holding a mutex.
> Fix go vet issues: example tests, returning a mutex copy

- README.md
Fixes #792 by adding an example of initializing a `Client` with support for SASL, which is accomplished via the `Transport` configuration.
> docs(readme): add example of using SASL with Client

- writer.go
This PR simplifies and fixes internal synchronization in the `kafka.Writer` type.
There were a few issues:
* marking the writer as closed was done via an atomic operations in `Close`, racing with the check in `WriteMessages`
* increments of the `partitionWriter` wait group was done asynchronously after starting goroutines, racing with calls to `Wait` on these wait groups
I removed the sync group in `partitionWriter` and instead managed the count of inflight operations globally on a single wait group in `Writer`; we only care about the writer's `Close` call to block until all inflight operations are done, there is no need to have a hierarchical synchronization scheme.
Fixes #778
> fix writer async close

- transport.go
- transport_test.go
Skip refresh metadata for errored topic, fixed the problem metadata refresh indefinitely, 
such as write message to a topic that not exist, but kafka disabled topic auto creation.
Fixes #806
Refer to the implementation of #673
> Skip refresh metadata for errored topic, fix #806

- .circleci/config.yml
- conn.go
Revert removal of high water mark check. Although this fixes nettest it's not the correct behavior.
Reverts segmentio/kafka-go#788
> Revert "Nettest fix"

- reader.go
- reader_test.go
This is a WIP and isn't ready to commit until I put a unit test together. 😄 
This PR adds a final commit upon exiting the consumer group when using the synchronous commit mode.  Otherwise, it's possible that we lose commits on generation end (or other events that initiate the end of a generation such as closing the reader).
Fixes #711
> Do a final commit on end consumer group generation for immediate commits

- batch.go
- message_reader.go
- message_test.go
- reader.go
- reader_test.go
Based off of https://github.com/segmentio/kafka-go/pull/807 and also related to https://github.com/segmentio/kafka-go/pull/709
```
Move the fix inside `Batch.readMessage`
The reasoning is that `Batch.readMessage` is normally where we update
the batch offset so the goal is to do this additional update to the
batch offset in the same location.
Also adjusts the test case retry so that the test case may finish
earlier than the previous sleep time while also giving the test more
time to finish to reduce flakiness.
The test case also now ensures that the final state is fully compacted
before declaring success.
```
The solution has been updated to jump to the last offset as indicated by the response header. In addition a test is added to ensure that the new way of moving offsets still works when …
> Fix batch offset when a batch has 0 messages

- README.md
The latest kafka-go version is v0.4.28, and v0.4.0 has been merged over a year ago. It seems like a good time to save some real estate space in the README and remove the migration guidelines.
> remove 0.4 migration docs + other README updates

- README.md
This PR replaces the use of "Golang" for "Go" in the README, and removes the suggestion to use kafka-go v0.2.5 which we don't really offer maintenance for anymore.
> README: fix go versions compatibility documentation

- README.md
- protocol/response.go
- protocol/response_test.go
when an io.ErrUnexpectedEOF is returned when reading
a correlation ID, attempt to detect if the messages
from the broker was a TLS Alert Message and decorate
the returned error
> attempt to detect improper TLS config

- transport.go
This behavior also matches the old dialer behavior.
> set ServerName on tls.Config even when InsecureSkipVeriy is true

- README.md
Since `msg` is formatted we should call `Printf` because `Println` doesn't support variadic arguments
> Fix logger example

- README.md
- writer.go
- writer_test.go
Add field AllowAutoTopicCreation to Writer struct.
It prevents the side-effect of creating missing topic.
Closes #872
> Add the field to avoid creating missing topic.

- protocol/conn.go
- protocol/protocol.go
- protocol/saslauthenticate/saslauthenticate.go
- writer_test.go
Potentially related to #868 and #795
> support saslAuthenticate v0 in protocol package

- message_reader.go
It seems the change in https://github.com/segmentio/kafka-go/pull/551 either did not make it to the main branch, or was reverted at some point.
It was reported in https://github.com/segmentio/kafka-go/issues/874.
I don't know under which conditions Kafka would return a negative header count but apparently kafka does this sometimes 🤷
> fix: don't assume the header count will be positive

- compress/zstd/zstd.go
As of v1.15.0, klauspost/compress/zstd now does not spawn internal goroutines if the encoding/decoder concurrency is set to 1, which means that we don't need the create intermediary objects to tie the lifetime of zstd encoders/decoders to via `runtime.SetFinalizer`.
https://github.com/klauspost/compress/issues/264
> upgrade github.com/klauspost/compress to v1.15.1 and remove the need for runtime finalizers

- error.go
Brings the list of error codes up to date with what is at https://kafka.apache.org/protocol.html#protocol_error_codes
> Bring the list of error codes up to date

- reader.go
When the reader logs an offset value, if the value is a special value,
i.e. FirstOffset / LastOffset, it will log something like
setting the offset ... from -2 to 20
With this change, it'll say "(first offset)" or "(last offset)",
respectively, for example:
setting the offset ... from (first offset) to 20
> Add "human readable" description for offset in reader logs

- writer.go
Introduced in https://github.com/segmentio/kafka-go/pull/873.
> Fix typo in Writer fields documentation

- .golangci.yml
- client_test.go
- compress/snappy/go-xerial-snappy/snappy_test.go
- conn.go
- conn_test.go
- consumergroup.go
- createtopics.go
- dialer_test.go
- discard_test.go
- example_consumergroup_test.go
- message_test.go
- protocol/protocol.go
- protocol/prototest/prototest.go
- protocol/record_batch_test.go
- read_test.go
- reader.go
- reader_test.go
- transport.go
- writer_test.go
This PR enables the [errorlint](https://github.com/polyfloyd/go-errorlint) linter in golangci-lint. This specifically ensures that errors are properly checked, avoiding things like direct equality (`==`) checks and type coercion/switch, to ensure as much compatibility with improvements to errors in go 1.13+.
This is a continuation of #877, but will need to be followed up by one more PR to enable another linter to ensure we wrap errors coming from external packages.
> enable errorlint linter and fix issues

- message_reader.go
Fixes https://github.com/segmentio/kafka-go/issues/909
> feat: reuse decompressed buffer to avoid allocating buffer whenever a batch is read. Fixes #909

- protocol/describeconfigs/describeconfigs.go
- protocol/describeconfigs/describeconfigs_test.go
While using this in production we ran into a panic where DescribeConfigs resulted in a *net.OpError (due to the kafka cluster rebalancing).
The panic was because we cast everything to *Response even though there are cases where it's an error. Handling this case with an error type seemed more appropriate.
This is a recreation of https://github.com/segmentio/kafka-go/pull/890 which maintains the original authors commits.
> fix: handle error in response

- go.mod
- go.sum
- kafka_test.go
- reader.go
- reader_test.go
This PR aims to change the handling of `OffsetOutOfRange` errors in the `Reader`, but includes some quirks to retain backwards-compatibility. This will fix #891 and makes #892 unnecessary.
In short, when a topic is re-created (ie: deleted and re-created with same name), any readers that are already running will begin encountering `OffsetOutOfRange` errors, but will retry them indefinitely, blocking the program from making progress. This error can also occur when a particular broker advances past the leader, so retrying made sense as this was usually temporary.
The original issue and PR related to this opted to automatically "reset" the offset when this error was encountered, but this felt a little too magical and I've opted instead to return an error to allow the client to handle it in …
> Reader: allow config to return OffsetOutOfRange errors

- .golangci.yml
- error.go
- findcoordinator_test.go
- joingroup.go
- joingroup_test.go
- leavegroup.go
- leavegroup_test.go
- protocol/consumer/consumer.go
- protocol/consumer/consumer_test.go
- protocol/joingroup/joingroup.go
- protocol/joingroup/joingroup_test.go
- protocol/leavegroup/leavegroup.go
- protocol/leavegroup/leavegroup_test.go
- protocol/syncgroup/syncgroup.go
- protocol/syncgroup/syncgroup_test.go
- syncgroup.go
- syncgroup_test.go
JoinGroup,SyncGroup,LeaveGroup
> add consumer group apis to client

- leavegroup_test.go
- syncgroup.go
- syncgroup_test.go
Fix some typos in the request structs for group functions.
> fix typos in group structs

- protocol/describeconfigs/describeconfigs.go
- protocol/describeconfigs/describeconfigs_test.go
- protocol/describegroups/describegroups.go
Fixing the rest of the issues pointed out by https://github.com/segmentio/kafka-go/pull/931
> protocol: Use standardized result type checking

- protocol/listgroups/listgroups.go
- protocol/protocol.go
In the event of a sudden network outage (such as a sudden wifi disconnection or vpn request to reconnect), the `ListGroups` method panics because the result is incorrectly asserted as Response, but is actually an `error` type (e.g. `context deadline exceeded` or `*net.OpError` etc)
> fix(protocol): fix type assertion error

- protocol/joingroup/joingroup.go
ProtocolType comes before ProtocolName
```
JoinGroup Response (Version: 7) => throttle_time_ms error_code generation_id protocol_type protocol_name leader member_id [members] TAG_BUFFER 
throttle_time_ms => INT32
error_code => INT16
generation_id => INT32
protocol_type => COMPACT_NULLABLE_STRING
protocol_name => COMPACT_NULLABLE_STRING
leader => COMPACT_STRING
member_id => COMPACT_STRING
members => member_id group_instance_id metadata TAG_BUFFER 
member_id => COMPACT_STRING
group_instance_id => COMPACT_NULLABLE_STRING
metadata => COMPACT_BYTES
```
> re-order protocol/joingroup response fields

- .gitignore
- README.md
- writer.go
Based on the discussion [here](https://github.com/segmentio/kafka-go/issues/894#issuecomment-1199788686)
Fixes https://github.com/segmentio/kafka-go/issues/894
> Updated Writer and Reader docs to show use of multiple brokers.

- error.go
We can't see the actual errors of our batch write request. It creates new error and this error does not contain any information about the error return fmt.Sprintf("kafka write errors (%d/%d)", err.Count(), len(err)). We need to see the detail of the error.
Issue thread: https://github.com/segmentio/kafka-go/issues/957
> Update WriteErrors error message

- reader.go
PR makes message `safetyTimeout` as `ReadBatchTimeout `  configurable because `SetReadDeadline` for msg could differentiate based on the network and  make it configurable instead of opinionated configuration
> #726 make kafka reader message ReadBatchTimeout configurable 

- offsetdelete.go
- offsetdelete_test.go
- protocol/offsetdelete/offsetdelete.go
- protocol/offsetdelete/offsetdelete_test.go
Closes #1009
The tests need kafka 2.4 to successfully run.
> Support for offsetdelete

- conn.go
- dialer_test.go
- kafka.go
- metadata.go
- protocol.go
- protocol_test.go
Add support for metadata requests with v6.
MSK Serverless fails with a EOF for all metadata requests with a version of less than 6.
This is one step towards fixing https://github.com/segmentio/kafka-go/issues/967
> Support metadata request v6

- writer.go
Fixes #1005 
Technically a breaking change but it seems simple enough for applications to address, any use of the `retries` metric prior to this change would have likely been erroneous anyways.
> change writer retries stat from summary to counter

- writer.go
- writer_test.go
Added Writer config to configure min and max delay between reties. No changes in the logic or default values.
> Add WriteBackoffMin/Max config to Writer 

- consumergroup.go
- consumergroup_test.go
- joingroup.go
- joingroup_test.go
- protocol/heartbeat/heartbeat.go
- reader_test.go
- syncgroup.go
- syncgroup_test.go
Moving the consumer group to the Client has introduced a number of bugs. This fixes a couple of them.
> Fixes for consumer group

- describeconfigs.go
- writer.go
Developers (at least me) don't always look at which version of the library is currently added to the project. 
I removed outdated parts in the documentation so that the hints in the IDE would not confuse users.
**UPD**: Fixed an inaccuracy in the description of the field for the struct `DescribeConfigsRequest`
> Removed the outdated part of the documentation

- go.mod
those two versions contained the conversion of the ConsumerGroup to the Client type. That conversion contained numerous bugs and had to be reverted
> retract v0.4.36-v0.4.37

- message.go
- writer_test.go
close #1054 
This PR adds a new field `metadata interface{}` into the `message` struct, which can be used to hold any information, this can be helpful for the application to do post work after confirming the message is delivered.
> add WriterData field to the message struct

- reader.go
Comment on `ReaderConfig.MaxAttempts` is confusing: word "deliver" in context of a kafka driver can be understood like "deliver over network", and it did not specify what exactly will be attempted.
> Change comment on MaxAttempts

- batch.go
- message_reader.go
Directly using batch.Read or through the Reader interface requires creating new batch using `conn.ReadBatchWith`. This causes the decompressed buffer to be allocated fresh and requires repeated calls to Grow and then it is discarded on batch.Close.
To avoid this, this patch acquires new buffer when creating newMessageSetReader and releases it in batch.Close.
> Use buffer pool for decompressed buffer

- conn.go
After [go 1.14](https://go.dev/doc/go1.14), go scheduler can interrupt without function call and can ensure that goroutines get fair access to the processor.  Moreover, it could decrease performance because of intentional goroutine switching.
> Remove runtime.Gosched

- deletegroups.go
- deletegroups_test.go
- protocol/deletegroups/deletegroups.go
- protocol/deletegroups/deletegroups_test.go
Implement DeleteGroups protocol and add it to Client.
> Add DeleteGroups function to Client

- balancer.go
- compress/compress.go
- fetch.go
- produce.go
- reader.go
- reader_test.go
- transport.go
- writer.go
- writer_test.go
A few things I noticed across the codebase.
> Fix various typos and disfluencies

- message_reader.go
Profiling shows that up to 40% of our allocations happen in r.markRead(): just to allocate a slice to pass the "remain" arg, which will be discarded because we don't run with r.debug=true.
```
Total:    64259028   64259028 (flat, cum) 41.57%
350            .          .           	if r.count == 0 { 
351            .          .           		panic("markRead: negative count") 
352            .          .           	} 
353            .          .           	r.count-- 
354            .          .           	r.unwindStack() 
355     64259028   64259028           	r.log("Mark read remain=%d", r.remain) 
356            .          .           } 
357            .          .            
358            .          .           func (r *messageSetReader) unwindStack() { 
359            .          . …
```
> Don't invoke r.log() if not r.debug

- writer.go
close #1101
* After a batch is resolved, record the batch duration immediately.
> add a new metric named `batchQueueTime` to track the batch time cost

- stats.go
This PR adds `Count` and `Sum` fields into `SummaryStats` and `DurationStats`. These fields are useful when converting stats into Prometheus counters or summaries. Here is how we use them in our code:
```go
type writerMetrics struct {
writer *kafka.Writer
// ignoring other metrics in this example
batchTime, batchBytes *summary
}
func (wm *writerMetrics) updateStats() {
ws := wm.writer.Stats()
// ignoring other metrics in this example
wm.batchTime.add(ws.BatchTime.Count, ws.BatchTime.Sum.Seconds()) // here we use new Count and Sum fields.
wm.batchBytes.add(ws.BatchBytes.Count, float64(ws.BatchBytes.Sum))
}
// summary is registered into Prometheus registrerer, see newSummary below.
type summary struct {
desc *prometheus.Desc
mu    sync.Mutex
count uint64
sum   float64
}
func …
```
> Add count/sum to SummaryStats and DurationStats.

- reader.go
Add explicit errors as arguments so anyone can handle them in the logger implementation.
We stumbled across issue that during Kafka rebalancing we have plenty of different error logs (EOF, Unexpected EOF, not a leader, etc.). The only possible way to handle that noise is to add some middleware logic into our implementation of logger. So, to have better backward compatibility it's better to not check against string values, but against errors explicitly.
> Not omit error in logger

- README.md
we often get issues reported about Readers not consuming messages which stems from a large MinBytes which is just copied from our examples. Remove that field so new users use the default value and the Reader behaviors more like what's expected by default.
> remove MinBytes from README examples

- createtopics.go
- createtopics_test.go
> CreateTopics: only suppress topic already exists errors

- writer.go
We have used pooled byte slices for the Message's `.Value`, after `.WriteMessages()` returned we re-used these byte slices and modified their content, this has lead to corrupted data being written when `.WriteMessages()` returned early due to a canceled context.
With this PR I'd like to make the warning in the comment a bit more explicit.
Signed-off-by: Mauro Stettler <mauro.stettler@gmail.com>
[A bit more context on stack overflow](https://stackoverflow.com/questions/76309028/kafka-consumers-receive-corrupted-messages-when-kafka-restarts/76377970)
> add additional warning on WriteMessages()

- message.go
- writer.go
- writer_test.go
Currently, the decision to include a message in a batch does not consider headers, so you can get payloads that are larger than intended if you are close to your upper limit and then include headers. This adds a new test for batching with headers that failed and then a fix was added to correct the failing test. This also updates another test that began failing once we included the header length in this calculation.
This closes #1050
> Writer: ensure batching logic factors in message headers

- offsetfetch.go
- offsetfetch_test.go
- protocol/offsetfetch/offsetfetch.go
#1115 
made the "Topics" filed of offsetfetch's Request (https://github.com/segmentio/kafka-go/blob/main/protocol/offsetfetch/offsetfetch.go#L11)  nullable in order to make it compliant with Kafka API specs
Setup: 
P1 ------> [T1] ------> {CG1} -------> C1
P12------> [T2] ------> {CG1} -------> C2
Test 1 driver
```package main
import (
"context"
"fmt"
"github.com/segmentio/kafka-go"
)
func main() {
fmt.Printf("START\n")
ctx := context.Background()
client := kafka.Client{Addr: kafka.TCP("localhost:9092")}
topicOffsets, err := client.OffsetFetch(ctx, &kafka.OffsetFetchRequest{GroupID: "cg1"})
if err != nil {
fmt.Printf("ERROR: %s\n", err.Error())
}
fmt.Printf("number of topics %d\n", len(topicOffsets.Topics))
for topic, offsets := range topicOffsets.Topics { …
```
> offsetfetch request topics are now nullable

- writer.go
This is done to make it easier to write better error logger implementations. For instance, when using IAM auth for MSK, the first write will fail after credentials rotate. The connection is re-negotiated and the retry is successful, but the logs are filled with errors. This lets us ignore the error of the first attempt, but log subsequent ones.
> Adds attempt number to log message when failing to write messages

- alteruserscramcredentials.go
- alteruserscramcredentials_test.go
- describeuserscramcredentials.go
- describeuserscramcredentials_test.go
- protocol/alteruserscramcredentials/alteruserscramcredentials.go
- protocol/alteruserscramcredentials/alteruserscramcredentials_test.go
- protocol/describeuserscramcredentials/describeuserscramcredentials.go
- protocol/describeuserscramcredentials/describeuserscramcredentials_test.go
- protocol/protocol.go
Support userscramcredentials APIs
[DescribeUserScramCredentials API Docs](https://kafka.apache.org/protocol#The_Messages_DescribeUserScramCredentials)
[AlterUserScramCredentials API Docs](https://kafka.apache.org/protocol#The_Messages_AlterUserScramCredentials)
I based this PR on similar work done here https://github.com/segmentio/kafka-go/pull/1119
> support userscramcredentials apis

- alterpartitionreassignments.go
- alterpartitionreassignments_test.go
- protocol/alterpartitionreassignments/alterpartitionreassignments.go
- protocol/alterpartitionreassignments/alterpartitionreassignments_test.go
- Allowed assigning to multiple topics with AlterPartitionReassignments
- Make BrokerIds in AlterPartitionReassignments nullable to support canceling ongoing partition reassignments
> Changed AlterPartitionReassignments request to support multiple topics

- createacls.go
- createacls_test.go
- resource.go
- resource_test.go
Add methods for parsing ACL related resources and converting them between their kafka-go and human readable versions
This is taken from Sarama https://github.com/IBM/sarama/blob/3ca69a884964f10c228a382d184b0d5005c342e1/acl_types.go#L35
> add methods for parsing and stringifying acl related resources

- balancer.go
- balancer_test.go
The motivation here is to try to get Kafka-Go's RR Balancer to batch more aggressively.  The RR Balancer naively iterates through the available partitions, putting a single message on each of them until the batch timeout.  If it could put x messages on each partition before moving onto the next one, it would still be evenly distributed, but batch better.
The coding approach was to bring in the same chunking mechanism our internal Bulrush library uses, but simplify it and adapt it for the code-style of Kafka-Go.
> Add Chunk Size to RR Balancer (Increased Batching Ability)

- balancer.go
https://github.com/segmentio/kafka-go/pull/1232 introduced a data race in the roundrobin balancer. It isn't a meaningful one, but still shows up when you use kafka-go as a library and run `go test -race`
> fix: data race in roundrobin balancer

- reader.go
Fix error in documentation for ReaderConfig.RetentionTime. Default value should be -1.
Fix #1244
> Fix RetentionTime error in documentation default is -1

- Makefile
As part of the Docker binary this will be updated more often and has
better support and newer features than the separate "docker-compose"
binary.
> Makefile: use docker compose not docker-compose

- error.go
- error_test.go
When someone is trying to check an errors.Is comparison of the struct MessageTooLargeError there is no good way to check that the underlying error `MessageSizeTooLarge`. By exposing the underlying error with this new method it allows end users to be able to make a comparison using errors.Is().
Add ErrorType method to MessageTooLargeError struct to support functionality with the errors.Is function.
closes #1293
> Add ErrorType method to MessageTooLargeError

- .circleci/config.yml
- addoffsetstotxn_test.go
- reader_test.go
- scripts/wait-for-kafka.sh
- txnoffsetcommit_test.go
This PR fixes at least 1 flaky test and a scenario when kafka is slow to start and the first tests in the suite just fail.
The cases are various but we have:
- topic creating not waiting before sending and reading
- timeouts
- kafka not started
I don't think this has solved them all, but I managed to get a local build passing as well as in CI, which I could not achieve without these changes.
> Fixes some flaky tests in the build as well as the case when tests start before kafka is ready

- reader_test.go
This test has been failing sporadically, especially against Kafka 2.8.1. It appears to be due to a race condition, and that version of Kafka may have slightly higher latency that explains why it happens so often there.
Proof this fixed it:
```bash
go test -count 10 --failfast -run TestRebalanceTooManyConsumers
PASS
ok      github.com/segmentio/kafka-go   103.900s
```
> chore: fix flaky TestRebalanceTooManyConsumers

- error.go
FencedInstanceID needs a corresponding title and description in order to get human-understandable error output when heartbeating with a reused instance id.
> Add title and description for FencedInstanceID

- batch.go
- createtopics.go
- describeclientquotas.go
- listoffset.go
- metadata.go
- protocol/record.go
- record.go
This PR fixes typos and improves comments across various types and functions in the codebase.
> docs: fix typos and comments

- listgroups.go
- listgroups_test.go
Currently, the protocol based ListGroups request does not include the [ProtocolType field](https://kafka.apache.org/protocol#The_Messages_ListGroups) in the response object (the deprecated V1 ListGroups response included it). It just returns GroupID and Coordinator.
This PR adds ProtocolType to that response object.
> feat: add ProtocolType to ListGroupsResponseGroup
